LOADERS = {
    ".csv": ("SimpleCSVReader", {}),
    ".docx": ("DocxReader", {}),
    ".eml": ("UnstructuredReader", {}),
    ".epub": ("UnstructuredReader", {}),
    ".html": ("UnstructuredReader", {}),
    ".md": ("MarkdownReader", {}),
    ".odt": ("PandasExcelReader", {}),
    ".pdf": ("PDFReader", {}),
    ".pptx": ("PptxReader", {}),
    ".txt": ("UnstructuredReader", {}),
    ".json": ("UnstructuredReader", {}),
    ".xls": ("PandasExcelReader", {}),
    ".xlsx": ("PandasExcelReader", {}),
}
