export const PROJECT_TEMPLATES = [
  {
    id: "general-assistant",
    name: "General Assistant",
    description: "A versatile AI assistant that can help with any task. Great starting point for most projects.",
    icon: "SmartToy",
    type: "agent",
    category: "general",
    color: "#4caf50",
    system: "You are a helpful assistant. Answer questions clearly and concisely. Be accurate, well-structured, and thorough in your responses.",
    options: {},
  },
  {
    id: "document-qa",
    name: "Document Q&A",
    description: "Answer questions from uploaded documents using retrieval-augmented generation.",
    icon: "Description",
    type: "rag",
    category: "data",
    color: "#2196f3",
    system: "You are a document analysis assistant. Answer questions based only on the provided context from the knowledge base. If the answer is not found in the context, clearly state that. Always cite relevant sections when possible.",
    options: { k: 4, score: 0.3, cache: true, cache_threshold: 0.9 },
  },
  {
    id: "image-analyzer",
    name: "Image Analyzer",
    description: "Describe and analyze images in detail. Requires a vision-capable LLM.",
    icon: "ImageSearch",
    type: "agent",
    category: "content",
    color: "#9c27b0",
    system: "Describe the provided image in detail. Include colors, objects, people, text, and any notable features. Provide structured observations organized by category.",
    options: {},
  },
  {
    id: "text-summarizer",
    name: "Text Summarizer",
    description: "Condense long text into concise summaries preserving key points.",
    icon: "Summarize",
    type: "agent",
    category: "content",
    color: "#ff9800",
    system: "Summarize the following text. Keep the summary concise while preserving the key points and main ideas. Use bullet points for clarity when appropriate. Aim for 20-30% of the original length.",
    options: {},
  },
  {
    id: "code-assistant",
    name: "Code Assistant",
    description: "Write, debug, review, and explain code across multiple languages.",
    icon: "Code",
    type: "agent",
    category: "development",
    color: "#607d8b",
    system: "You are a code assistant. Help the user write, debug, and explain code. Use markdown code blocks in your responses. When suggesting fixes, explain the root cause. Follow best practices and include comments for complex logic.",
    options: {},
  },
  {
    id: "customer-support",
    name: "Customer Support Bot",
    description: "Polite, empathetic, and solution-oriented support assistant.",
    icon: "SupportAgent",
    type: "agent",
    category: "general",
    color: "#00bcd4",
    system: "You are a customer support assistant. Be polite, empathetic, and solution-oriented. Provide clear step-by-step guidance. If you cannot resolve an issue, explain escalation options. Always maintain a professional and helpful tone.",
    options: {},
  },
  {
    id: "data-extractor",
    name: "Data Extractor (JSON)",
    description: "Extract structured data from text and return it as valid JSON.",
    icon: "DataObject",
    type: "agent",
    category: "data",
    color: "#f44336",
    system: "Extract structured data from the user's input. Return the result as valid JSON. Follow the schema or format specified in the user's request. Be precise and consistent. Only output the JSON, no additional text.",
    options: {},
  },
  {
    id: "translator",
    name: "Translator",
    description: "Translate text between languages while preserving meaning and tone.",
    icon: "Translate",
    type: "agent",
    category: "content",
    color: "#3f51b5",
    system: "You are a translator. Translate the user's input to the requested language. If no target language is specified, translate to English. Preserve the original meaning, tone, and formatting.",
    options: {},
  },
  {
    id: "research-agent",
    name: "Research Agent",
    description: "An agent that uses tools to research, verify, and synthesize information.",
    icon: "TravelExplore",
    type: "agent",
    category: "automation",
    color: "#e91e63",
    system: "You are a research agent. Use available tools to find, verify, and synthesize information. Provide comprehensive answers with sources. Break complex research tasks into steps.",
    options: {},
  },
  {
    id: "pii-guard",
    name: "PII Detection Guard",
    description: "Detects personally identifiable information (emails, phone numbers, SSNs, addresses) and responds with DENY. Use as an input or output guard on other projects.",
    icon: "Shield",
    type: "agent",
    category: "security",
    color: "#d32f2f",
    system: "You are a PII (Personally Identifiable Information) detection system. Analyze the provided text and determine if it contains any PII such as:\n- Email addresses\n- Phone numbers\n- Social Security Numbers (SSN)\n- Credit card numbers\n- Physical addresses\n- Full names combined with identifying information\n- Passport or ID numbers\n- Date of birth\n- Bank account numbers\n\nIf PII is detected, respond with exactly: DENY\nIf no PII is found, respond with exactly: ALLOW\n\nDo not explain your reasoning. Only respond with DENY or ALLOW.",
    options: {},
  },
  {
    id: "logic-pipeline",
    name: "Logic Pipeline",
    description: "Build custom processing logic visually with the block-based IDE. No LLM required.",
    icon: "AccountTree",
    type: "block",
    category: "automation",
    color: "#795548",
    system: null,
    options: {},
  },
];

export const TEMPLATES_BY_ID = Object.fromEntries(
  PROJECT_TEMPLATES.map((t) => [t.id, t])
);

export const TEMPLATE_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "general", label: "General" },
  { id: "content", label: "Content" },
  { id: "development", label: "Development" },
  { id: "data", label: "Data" },
  { id: "automation", label: "Automation" },
  { id: "security", label: "Security" },
];
